name: Docker Compile Check + Lint

on:
  push:     # All branches
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make docker-compose openssl

    - name: Generate SSL and JWT Secret
      run: make ssl jwt-secret

    - name: Build Docker containers
      run: make all

    - name: Wait for services to start
      run: sleep 10

    - name: Check frontend TypeScript build
      run: docker exec --workdir /var/www/html frontend npm run build

    - name: Run backend ESLint (ESLint 9 flat config)
      run: docker exec --workdir /backend backend npx eslint ./srcs

    - name: Shutdown containers
      if: always()
      run: make down
