name: Docker Compile Check + Lint

on:
  push:     # All branches
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make docker-compose openssl

    - name: Generate SSL and JWT Secret
      run: make ssl jwt-secret

    - name: Build Docker containers
      run: make all

    - name: Wait for services to start
      run: sleep 10

    - name: Run frontend build and save result
      id: frontend
      run: |
        docker exec --workdir /var/www/html frontend npm run build
      continue-on-error: true

    - name: Run backend ESLint and save result
      id: backend
      run: |
        docker exec --workdir /backend backend npx eslint ./srcs
      continue-on-error: true

    # - name: Run backend tests
    #   run: docker exec --workdir /backend backend npm run test
    #   continue-on-error: true # Allow failure for tests, so we can still check lint

    - name: Fail job if frontend or backend failed
      run: |
        echo "Frontend status: ${{ steps.frontend.outcome }}"
        echo "Backend status: ${{ steps.backend.outcome }}"
        if [[ "${{ steps.frontend.outcome }}" != "success" || "${{ steps.backend.outcome }}" != "success" ]]; then
          echo "❌ One or more steps failed"
          exit 1
        fi

    - name: Shutdown containers
      if: always()
      run: make down
