name: Docker Compile Check + Lint

on:
  push:     # All branches
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make docker-compose openssl

    - name: Generate SSL and JWT Secret
      run: make ssl jwt-secret

    - name: Build Docker containers
      run: make all

    - name: Wait for services to start
      run: sleep 10

    - name: Check frontend TypeScript build
      run: docker exec --workdir /var/www/html frontend npm run build
      continue-on-error: true # Allow failure for frontend build, so backend can still run

    - name: Run backend ESLint (ESLint 9 flat config)
      run: docker exec --workdir /backend backend npx eslint ./srcs
      continue-on-error: true # Allow failure for ESLint, so we can still run tests

    # - name: Run backend tests
    #   run: docker exec --workdir /backend backend npm run test
    #   continue-on-error: true # Allow failure for tests, so we can still check lint

    - name: Fail if previous steps had errors
      run: exit 1
      if: ${{ failure() }}
      
    - name: Shutdown containers
      if: always()
      run: make down
